### ISSUE TITLE
How do I deploy in k8s?

### ISSUE THREAD

**Issue by ShaPoHun** [kubeshark/worker#2]
I learned about this project from the official documentation
but
How do I deploy in k8s?

**Comment by mertyildiran** [comment]
Use `kubeshark tap` command to deploy in K8s: https://github.com/kubeshark/kubeshark#getting-started

Just worker by itself has no real use. It works together with the Hub and deployed as a [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/).

Use `-r` and `-t` flags with ``kubeshark tap` command to set a custom Docker registry and Docker tag if you want to test a custom build of the worker.
