### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zhangbo1882** [kubeshark/worker#5]
[Tue Dec 20 23:59:10][#23# ] (master)$make build
go build -ldflags="-extldflags=-static -s -w" -mod=vendor -o worker .

vendor/github.com/knightsc/gapstone/arm64_constants.go:1706:24: could not determine kind of name for C.ARM64_INS_LDNF1SH
vendor/github.com/knightsc/gapstone/arm64_constants.go:1707:24: could not determine kind of name for C.ARM64_INS_LDNF1SW
vendor/github.com/knightsc/gapstone/arm64_constants.go:1708:24: could not determine kind of name for C.ARM64_INS_LDNF1W
vendor/github.com/knightsc/gapstone/arm64_constants.go:1710:24: could not determine kind of name for C.ARM64_INS_LDNT1B
vendor/github.com/knightsc/gapstone/arm64_constants.go:1711:24: could not determine kind of name for C.ARM64_INS_LDNT1D
vendor/github.com/knightsc/gapstone/arm64_constants.go:1712:24: could not determine kind of name for C.ARM64_INS_LDNT1H
vendor/github.com/knightsc/gapstone/arm64_constants.go:1713:24: could not determine kind of name for C.ARM64_INS_LDNT1W
vendor/github.com/knightsc/gapstone/arm64_constants.go:1717:24: could not determine kind of name for C.ARM64_INS_LDRAA
vendor/github.com/knightsc/gapstone/arm64_constants.go:1718:24: could not determine kind of name for C.ARM64_INS_LDRAB
vendor/github.com/knightsc/gapstone/arm64_constants.go:1724:24: could not determine kind of name for C.ARM64_INS_LDSET
vendor/github.com/knightsc/gapstone/arm64_constants.go:1725:24: could not determine kind of name for C.ARM64_INS_LDSETA
vendor/github.com/knightsc/gapstone/arm64_constants.go:1726:24: could not determine kind of name for C.ARM64_INS_LDSETAB
vendor/github.com/knightsc/gapstone/arm64_constants.go:1727:24: could not determine kind of name for C.ARM64_INS_LDSETAH
vendor/github.com/knightsc/gapstone/arm64_constants.go:1728:24: could not determine kind of name for C.ARM64_INS_LDSETAL
vendor/github.com/knightsc/gapstone/arm64_constants.go:1729:24: could not determine kind of name for C.ARM64_INS_LDSETALB
vendor/github.com/knightsc/gapstone/arm64_constants.go:1730:24: could not determine kind of name for C.ARM64_INS_LDSETALH
vendor/github.com/knightsc/gapstone/arm64_constants.go:1731:24: could not determine kind of name for C.ARM64_INS_LDSETB

**Comment by zhangbo1882** [comment]
My build system is a ubuntu x86 machine.

**Comment by mertyildiran** [comment]
@zhangbo1882 install [these dependencies](https://github.com/kubeshark/worker/blob/master/.github/workflows/linter.yml#L29-L35) and run `make`

**Comment by zhangbo1882** [comment]
After install the dependencies.  I met another error.

[Mon Jan 02 20:31:11][#26# ] (master)$make
go build -ldflags="-extldflags=-static -s -w" -o worker .
# github.com/kubeshark/worker
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-401277725/000055.o: in function `mygetgrouplist':
/_/os/user/getgrouplist_unix.go:15: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-401277725/000054.o: in function `mygetgrgid_r':
/_/os/user/cgo_lookup_unix.go:37: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-401277725/000054.o: in function `mygetgrnam_r':
/_/os/user/cgo_lookup_unix.go:42: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-401277725/000054.o: in function `mygetpwnam_r':
/_/os/user/cgo_lookup_unix.go:32: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-401277725/000054.o: in function `mygetpwuid_r':
/_/os/user/cgo_lookup_unix.go:27: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-401277725/000004.o: in function `_cgo_2ac87069779a_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): in function `pcap_nametoaddr':
(.text+0x9): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): in function `pcap_nametonetaddr':
(.text+0x101): warning: Using 'getnetbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): in function `pcap_nametoproto':
(.text+0x583): warning: Using 'getprotobyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-401277725/000029.o: in function `_cgo_46644277c029_Cfunc_cs_regs_access':
/tmp/go-build/cgo-gcc-prolog:235: undefined reference to `cs_regs_access'

**Comment by mertyildiran** [comment]
@zhangbo1882 use the `make` command: https://github.com/kubeshark/worker/blob/master/Makefile

Use Go version `1.17`

These are warnings (**not errors**) and it's fine to see them:

```
go build -ldflags="-extldflags=-static -s -w" -o worker .
# github.com/kubeshark/worker
/usr/bin/ld: /tmp/go-link-3510300903/000054.o: in function `mygetgrouplist':
/usr/local/go/src/os/user/getgrouplist_unix.go:18: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3510300903/000053.o: in function `mygetgrgid_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:40: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3510300903/000053.o: in function `mygetgrnam_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:45: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3510300903/000053.o: in function `mygetpwnam_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:35: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3510300903/000053.o: in function `mygetpwuid_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:30: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3510300903/000004.o: in function `_cgo_3c1cec0c9a4e_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): in function `pcap_nametoaddr':
(.text+0x9): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): in function `pcap_nametonetaddr':
(.text+0x101): warning: Using 'getnetbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): in function `pcap_nametoproto':
(.text+0x583): warning: Using 'getprotobyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

I'm not sure what's the error in your case. Please format your comments.

**Comment by zhangbo1882** [comment]
I think the build error is :

> /usr/bin/ld: /tmp/go-link-3045307821/000029.o: in function `_cgo_46644277c029_Cfunc_cs_regs_access':
> /tmp/go-build/cgo-gcc-prolog:235: undefined reference to `cs_regs_access'
> collect2: error: ld returned 1 exit status

make: *** [Makefile:20: build] Error 2

**Comment by mertyildiran** [comment]
@zhangbo1882 your Capstone installation has issues, see:
- https://www.capstone-engine.org/op_access.html
- https://github.com/bnagy/gapstone/commit/cebe3ed7c1eb853c720719e3544a166fc55ff48c
- https://github.com/capstone-engine/capstone/issues/874#issuecomment-287423690
